serial_link_client: # <- THIS MUST MATCH THE NODE NAME
  ros__parameters:
    pose_error_tolerance:
        position: 0.1                                       # In meters
        orientation: 0.05                                   # In radians
    joint_error_tolerances: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]   # In radians
